using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._ES.Keypad.Ui;

[GenerateTypedNameReferences]
public sealed partial class ESKeypadWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;

    public ESKeypadWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void SetEntity(EntityUid uid)
    {
        if (!_entityManager.EntityExists(uid))
            return;

        Title = Loc.GetString("es-keypad-menu-ui-title", ("name", _entityManager.GetComponent<MetaDataComponent>(uid).EntityName));
        Keypad.SetEntity(uid);
    }
}

